/* tools/answer-key.js — regenerates ANSWER_KEY.md from the live data.
 *
 *   node tools/answer-key.js > ANSWER_KEY.md
 */
const fs = require('fs');
const path = require('path');

global.window = { addEventListener() {} };
global.document = { addEventListener() {} };
global.localStorage = { getItem() { return null; }, setItem() {}, removeItem() {} };
const src = path.join(__dirname, '..', 'src', 'js');
for (const f of ['groups.js', 'strain.js', 'geometry.js', 'molecules.js', 'draw.js', 'quiz.js', 'scorm.js', 'app.js']) {
  (0, eval)(fs.readFileSync(path.join(src, f), 'utf8'));
}

const fmt = STRAIN.fmt;
const out = [];
const P = (s = '') => out.push(s);
const POS = { 0: 'top', 60: 'upper right', 120: 'lower right', 180: 'bottom', 240: 'lower left', 300: 'upper left' };
const name = (g) => GROUPS[g].label + (g === 'Hr' ? ' (red)' : g === 'Hb' ? ' (blue)' : '');

function parts(mol, phi) {
  const p = GEOM.breakdownAt(mol, phi);
  if (!p.length) return 'nothing';
  return p.map((x) => `${x.label} ${x.kind} ${x.n > 1 ? x.n + ' × ' : ''}${fmt(x.cost)}`).join(' + ');
}

function conf(mol, phi) {
  const n = conformationName(mol, phi);
  const r = mol.vocab === 'ethane' ? null : refRelation(mol, phi);
  return n + (r && mol.vocab !== 'butane' ? ` (${r})` : '');
}

function figText(f) {
  if (f.newman) {
    const m = molecule(f.newman);
    return `Newman projection of ${m.name} at ${f.phi}° — ${conf(m, f.phi)}, ${fmt(GEOM.energyAt(m, f.phi))} kJ/mol`;
  }
  if (f.zigzag) { const m = molecule(f.zigzag); return `wedge/dash drawing of ${m.tag || m.name}`; }
  if (f.graph) return `energy curve of ${molecule(f.graph).name} with points ` +
    Object.keys(f.letters).map((k) => `${k} = ${f.letters[k]}°`).join(', ');
  return '';
}

P('# Answer key — Newman projections');
P();
P('Generated by `node tools/answer-key.js > ANSWER_KEY.md`. Do not edit by hand: change the data in');
P('`src/js/` and regenerate.');
P();
P('All energies are in kJ/mol and are sums of entries in the strain table below (0 = no strain). Dihedral');
P('angles are measured clockwise from the front reference group to the back one, as seen in the Newman');
P('projection.');
P();

/* ---------------------------------------------------------------- table */

P('## The strain table');
P();
P('| Interaction | Eclipsed | Gauche | Source of eclipsed value | Source of gauche value |');
P('| --- | ---: | ---: | --- | --- |');
for (const r of STRAIN.ROWS) {
  P(`| ${STRAIN.NAMES[r[0]]} / ${STRAIN.NAMES[r[1]]} | ${fmt(r[2])} | ${fmt(r[3])} | ${STRAIN.SOURCES[r[4]]} | ${STRAIN.SOURCES[r[5]]} |`);
}
P();

/* ---------------------------------------------------------------- builds */

P('## Builds');
P();
P('Every build is checked against the Newman projection computed from the drawing. Turning the whole');
P('projection by 120° or 240° is accepted, because it is the same view with the head tilted. Looking from');
P('the eye with the front chain group straight up, every **wedge lands on the left** and every **dash on the');
P('right**; the back chain group is at the bottom.');
P();
for (const s of App.STEPS.filter((x) => x.kind === 'build')) {
  const m = molecule(s.mol);
  const nm = GEOM.newmanOf(m);
  const [F, B] = m.carbons;
  P(`### ${s.title.replace(/’/g, "'")}`);
  P();
  P(`Drawing: ${F} has ${name(m.front.anchor)} in the page, ${name(m.front.wedge)} on a wedge, ` +
    `${name(m.front.dash)} on a dash. ${B} has ${name(m.back.anchor)} in the page, ` +
    `${name(m.back.wedge)} on a wedge, ${name(m.back.dash)} on a dash.`);
  P();
  P(`| Front carbon (${F}) | Back carbon (${B}) |`);
  P('| --- | --- |');
  const rows = [[0, 60], [120, 180], [240, 300]];
  for (const [fa, ba] of rows) {
    const f = nm.front.find((q) => q.a === fa), b = nm.back.find((q) => q.a === ba);
    P(`| ${POS[fa]}: ${name(f.g)} | ${POS[ba]}: ${name(b.g)} |`);
  }
  P();
  P(`Drawn conformation: ${conf(m, GEOM.phi0(m))}, ${fmt(GEOM.energyAt(m, GEOM.phi0(m)))} kJ/mol.`);
  P();
}

/* ---------------------------------------------------------------- energies */

P('## Energy at every named angle');
P();
for (const id of Object.keys(MOLECULES).filter((k) => MOLECULES[k].front)) {
  const m = molecule(id);
  const best = bestStaggered(m);
  P(`### ${m.tag ? m.tag + ' — ' : ''}${m.name} (\`${id}\`), looking down ${m.carbons[0]}–${m.carbons[1]}`);
  P();
  P(`x axis: ${m.axis}. Best staggered conformation: ${best.phi}°, ${fmt(best.e)} kJ/mol.`);
  P();
  P('| Angle | Conformation | Energy | Where it comes from |');
  P('| ---: | --- | ---: | --- |');
  for (const n of namedEnergies(m)) {
    P(`| ${n.phi}° | ${conf(m, n.phi)} | ${fmt(n.e)} | ${parts(m, n.phi)} |`);
  }
  P();
}

/* ---------------------------------------------------------------- predictions */

P('## Predictions (never graded)');
P();
for (const s of App.STEPS) {
  if (s.kind === 'find') {
    P(`- **${s.title}** — ${s.predict.q} *Answer: ${s.predict.choices[s.predict.answer]}.* ${s.predict.reveal}`);
  }
}
P('- **Swap the group on C2** — which group on the front carbon is anti to the back CH₃ in the lowest ' +
  'conformation? ' + MOLECULES.SWAP_ORDER.filter((x) => x !== 'Br').map((x) => {
    const id = { Cl: 'chlorobutane', I: 'iodobutane', CH3: 'methylbutane', iPr: 'dimethylpentane', tBu: 'trimethylpentane' }[x];
    const m = molecule(id), best = bestStaggered(m);
    const nm = GEOM.newmanAt(m, best.phi);
    const back = nm.back.find((q) => q.role === 'anchor').a;
    const anti = nm.front.find((q) => STRAIN.gap(q.a, back + 180) === 0).g;
    return `${GROUPS[x].label}: *${GROUPS[anti].label}* (${fmt(best.e)} kJ/mol)`;
  }).join('; ') + '.');
P('- **Put the bromines anti** — with the Br atoms anti, Molecule A\'s CH₃ groups are *anti* and ' +
  'Molecule B\'s are *gauche*. Replacing Br by I makes the halogen-gauche conformations *go up*.');
P('- **Sketches** — students drag the predicted curve; the activity compares the number of peaks and the ' +
  'positions of the highest and lowest points with the real curve.');
P();

/* ---------------------------------------------------------------- quizzes */

P('## Checkpoint questions (graded)');
P();
P(`Each attempt draws ${Object.keys(QUIZZES).map((k) => QUIZZES[k].draw).join(' + ')} = ${App.GRADED} questions. ` +
  'Core questions (★) are always drawn; the rest of each checkpoint is filled at random from its pool. ' +
  'The first answer counts.');
P();
for (const k of Object.keys(QUIZZES)) {
  const Q = QUIZZES[k];
  P(`### ${Q.title} — ${Q.draw} of ${Q.pool.length}`);
  P();
  Q.pool.forEach((q, i) => {
    const core = Q.core.includes(q.id) ? ' ★' : '';
    P(`${i + 1}. **${q.q}**${core} \`${q.id}\``);
    if (q.fig) P(`   - Figure: ${figText(q.fig)}`);
    const ans = typeof q.choices[0] === 'string' ? q.choices[0] : figText(q.choices[0]);
    P(`   - Answer: ${ans}`);
    const wrong = q.choices.slice(1).map((c) => typeof c === 'string' ? c : figText(c));
    P(`   - Distractors: ${wrong.join(' · ')}`);
    P(`   - Explanation shown: ${q.why}`);
  });
  P();
}

process.stdout.write(out.join('\n') + '\n');
